### ISSUE TITLE
Compiled app?

### ISSUE THREAD

**Issue by cukabeka** [TomHarte/CP-M-for-OS-X#10]
Hi, I was looking to find an installation instruction or something.. Is there a DMG or compiled app available?

**Comment by gferluga** [comment]
You can easy build with Xcode.
To launch a CP/M program, locate its .COM in the Finder and double click.

**Comment by TomHarte** [comment]
Apologies, missed this somehow. Compiled builds are hidden in the 'Releases' tab; [this is the latest](https://github.com/TomHarte/CP-M-for-OS-X/releases/tag/0.7.1).
